### ISSUE TITLE
Update link in UG to be jar file for v1.4

### ISSUE THREAD

**Issue by tau-bar** [AY2122S1-CS2103T-W13-4/tp#268]
![image](https://user-images.githubusercontent.com/61085398/140723318-892f904e-8dee-4e35-b9c3-cb9e4a2d4a4a.png)

Referring to here.

**Comment by YeluriKetan** [comment]
I think the purpose of the link was to just point it to the `releases` page, so that the user can download the latest file irrespective of when they are doing it.
So making it point to the `releases` page would make more sense, in my opinion, than to point it to one particular version and update the link everytime a new version is released.

**Comment by MarcusTXK** [comment]
I agree with @YeluriKetan , lets leave the link as it is.
